FROM maven:3.8.6-openjdk-11 as build
LABEL author="naveen"
ARG BRANCH="main"
RUN git clone https://github.com/gopijammula/MySpringPetclinicClone.git && \
    cd MySpringPetclinicClone && \
    git checkout ${BRANCH} && \
    mvn package
# jar location /spring-petclinic/target/spring-petclinic-2.7.3.jar
#  Building jar: /spring-petclinic/target/spring-petclinic-2.7.3.jar
# Building jar: /home/GOPI/MySpringPetclinicClone/target/spring-petclinic-2.7.3.jar
FROM openjdk:11
LABEL project="petclinic"
LABEL author="devops team"
EXPOSE 8080
COPY --from=build /MySpringPetclinicClone/target/spring-petclinic-2.7.3.jar /spring-petclinic-2.7.3.jar
CMD ["java", "-jar", "/spring-petclinic-2.7.3.jar"]
